# Generated by Django 5.0 on 2023-12-19 03:11

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='YogaBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'yoga_user',
                'indexes': [models.Index(fields=['email'], name='yoga_user_email_8f4efa_idx')],
            },
        ),
        migrations.CreateModel(
            name='YogaBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('yoga_users', models.ManyToManyField(blank=True, related_name='yoga_batches', to='yoga.yogabooking')),
            ],
            options={
                'db_table': 'yoga_batch',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='YogaTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timespan', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='yoga.yogabatch')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='created', max_length=30)),
                ('yoga_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='yoga.yogabatch')),
                ('yoga_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='yoga.yogabooking')),
                ('yoga_timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='yoga.yogatimings')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.AddConstraint(
            model_name='yogatimings',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('timespan', '&&')], name='exclude_overlapping_timings'),
        ),
    ]
