# Generated by Django 5.0 on 2023-12-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0003_remove_yogabatch_yoga_users_yogabooking_yoga_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogabooking',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='yogabooking',
            unique_together={('email', 'yoga_batch')},
        ),
    ]
