# Generated by Django 5.0 on 2023-12-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0004_alter_yogabooking_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yogabooking',
            unique_together=set(),
        ),
    ]
